print(bool([]))
print(bool(()))
print(bool({}))
print(bool(0))
print(bool(0.0))
print(bool(''))
print(bool('---------'))
print(bool('  '))
print(bool(1))
print(bool(-1))
print(bool('a'))
print(bool([1, 2, 3]))
