#Python Built-in Functions
print(abs(-1))
print(all([1, 2, 3, 4, 5, 6]))
print(any([0, 0, 0, True]))
print('1 -----')
print(bool(''))
print(bool(' '))
print('2 -----')
print(bool(1))
print(bool(0))
print('3 -----')
print(chr(65))
print(chr(97))
print('4 -----')
print(ord('A'))
print(ord('a'))
print('5 -----')
print(dict([('one', '1'), ('two', '2')]))
print('6 -----')
print(float(10))
print(float(10.1))
print('7 -----')
print(len(set('aabbbcc')))
